insert into archetypes values(101,'Blue-Eyes','UR',5,'when in doubt summon a giant dragon');
insert into archetypes values(102,'Dark Magician','UR',7,'Bring out the purple magician to make enemy decks go bye bye');
insert into archetypes values(103,'Sky Strikers','SR',10,'the more spell cards you have in the graveyard the better');
insert into archetypes values(104,'eldlich','UR',10,'Traps and a zombie are your best friends');
insert into archetypes values(105,'Silent','R',8,'Hope you can evolve the low level ones fast enough to stop their back-row');
insert into archetypes values(106,'Armed Dragon','SR',7,'Evolve your giant dragon then say bye to your hand');
insert into archetypes values(107,'Utopia','UR',6,'Xyz summon until you cant anymore then set up negates');
insert into archetypes values(108,'Blackwing','UR',8,'Bring out an odd bird then just keep stopping attacks');
insert into archetypes values(109,'junk','UR',10,'Revive and summon monsters from your grave then synchro into a boss monster');
insert into archetypes values(110,'stardust','UR',10,'Bring out Stardust Dragon then hope your opponent dosent do anything crazy');
insert into archetypes values(111,'Cyber Dragon','UR',7,'Make Mechanical dragons then start blasting');
insert into archetypes values(112,'Swordsoul','UR',3,'Summon Baronne de fleur then win');
insert into archetypes values(113,'Fallen of Albaz','UR',3,'Summon mirrojade iceblade dragon then win');
insert into archetypes values(114,'Kuriboh','SR',10,'discard to not take damage');
insert into archetypes values(115,'Elemental Hero','SR',9,'Summon a hero needed for the situation');
insert into archetypes values(116,'Onomatopia','UR',7,'Swarm the feild with long monster titles');
insert into archetypes values(117,'Photon','UR',5,'When in doubt summon a glowy dragon');
insert into archetypes values(118,'Odd-eyes','UR',5,'Summon a dragon to summon your entire hand');
insert into archetypes values(119,'sacred beasts','UR',5,'hope you dont like your spells and traps');
insert into archetypes values(120,'Red-Eyes','SR',8,'when in doubt summon a dragon that does everything at once');